//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrieuTruongGiang_2021603645.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public string sbd { get; set; }
        public string hoten { get; set; }
        public string anhduthi { get; set; }
        public Nullable<int> malop { get; set; }
        public Nullable<double> diemthi { get; set; }
    
        public virtual LopHoc LopHoc { get; set; }
    }
}
